version: "3"
services:

  nginx:
    image: nginx:1.27.3-alpine
    ports:
      - "8080:80"
    volumes:
      - /srv/flask/nginx.conf:/etc/nginx/conf.d/default.conf

  flask:
    build:
      context: /srv/flask/
    image: flask:0.0.0
    ports:
      - 5000:5000
