
# Documentation: https://docs.docker.com/reference/compose-file/

version: "3"
services:

  nginx:
    image: nginx:1.27.3-alpine
    ports:
      - "8080:80"
    volumes:
      - /srv/flask/nginx.conf:/etc/nginx/conf.d/default.conf

  flask:
    build: /srv/flask/
    image: flask:0.0.0
    ports:
      - 5000:5000

  mysql:
    image: mysql:9.2.0
    volumes:
      - /srv/flask/mysql.conf:/etc/mysql/my.cnf
      - /srv/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecretlool
