
# Documentation: https://docs.docker.com/reference/compose-file/

version: "3"
services:

  nginx:
    image: nginx:1.27.3-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: EXAMPLE
      MYSQL_DATABASE: EXAMPLE
      MYSQL_USER: EXAMPLE
      MYSQL_PASSWORD: EXAMPLE
    ports:
      - 7070:7070
    volumes:
      - ./src/mysql.conf:/etc/mysql/my.cnf
      - ./db:/var/lib/mysql

  flask:
    build: ./src/
    image: flask:0.0.1
    depends_on:
      - nginx
      - mysql
    environment:
      # These variables must reflect the values from the mysql container above
      FLASK_DB_HOST: mysql
      FLASK_DB_PORT: 7070
      FLASK_DB_USER: EXAMPLE
      FLASK_DB_PASSWORD: EXAMPLE
      FLASK_DB_DATABASE: EXAMPLE
    ports:
      - 5000:5000

