
# Documentation: https://docs.docker.com/reference/compose-file/

version: "3"
services:

  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: EXAMPLE
      MYSQL_DATABASE: EXAMPLE
      MYSQL_USER: EXAMPLE
      MYSQL_PASSWORD: EXAMPLE
    # Allows mysql to change it's thread prios, don't know why it has to...
    # Source: https://stackoverflow.com/a/55706057
    cap_add:
      - SYS_NICE
    ports:
      - 7070:7070
    volumes:
      - ./src/mysql.conf:/etc/mysql/my.cnf
      - ./db:/var/lib/mysql

  flask:
    build: ./src/
    image: flask:0.0.1
    depends_on:
      - mysql
    environment:
      # These variables must reflect the values from the mysql container above
      DB_HOST: mysql
      DB_PORT: 7070
      DB_USER: EXAMPLE
      DB_PASSWORD: EXAMPLE
      DB_DATABASE: EXAMPLE
      DB_DELAY: 3
    ports:
      - 5000:5000

  nginx:
    image: nginx:1.27.3-alpine
    depends_on:
      - flask
    ports:
      - "8080:80"
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf

