-- MySQL Script generated by MySQL Workbench
-- Mon Feb 17 23:16:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema base
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base` DEFAULT CHARACTER SET utf8 ;
USE `base` ;

-- -----------------------------------------------------
-- Table `base`.`Connectors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`Connectors` (
  `idconnector` INT NOT NULL AUTO_INCREMENT,
  `gender` INT NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idconnector`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idconnector_UNIQUE` ON `base`.`Connectors` (`idconnector` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `base`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`Products` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `price` FLOAT NOT NULL,
  `in_stock` INT NOT NULL,
  `standard` FLOAT NOT NULL,
  `length` FLOAT NOT NULL,
  `color` VARCHAR(10) NOT NULL,
  `ImageFileName` VARCHAR(45) NULL,
  `connector1` INT NOT NULL,
  `connector2` INT NOT NULL,
  PRIMARY KEY (`idproduct`),
  CONSTRAINT `fk_Products_USB_Connections1`
    FOREIGN KEY (`connector1`)
    REFERENCES `base`.`Connectors` (`idconnector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_USB_Connections2`
    FOREIGN KEY (`connector2`)
    REFERENCES `base`.`Connectors` (`idconnector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Products_USB_Connections1_idx` ON `base`.`Products` (`connector1` ASC) VISIBLE;

CREATE INDEX `fk_Products_USB_Connections2_idx` ON `base`.`Products` (`connector2` ASC) VISIBLE;

CREATE UNIQUE INDEX `idproduct_UNIQUE` ON `base`.`Products` (`idproduct` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `base`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`Users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `role` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(10) NULL,
  `last_name` VARCHAR(10) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Email_UNIQUE` ON `base`.`Users` (`email` ASC) VISIBLE;

CREATE UNIQUE INDEX `idusers_UNIQUE` ON `base`.`Users` (`iduser` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `base`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`Orders` (
  `iduser` INT NOT NULL,
  `idproduct` INT NOT NULL,
  `amount` INT UNSIGNED NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`iduser`, `idproduct`),
  CONSTRAINT `fk_ShoppingCarts_Users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `base`.`Users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ShoppingCarts_Products1`
    FOREIGN KEY (`idproduct`)
    REFERENCES `base`.`Products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ShoppingCarts_Products1_idx` ON `base`.`Orders` (`idproduct` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `base`.`CustomerReviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base`.`CustomerReviews` (
  `iduser` INT NOT NULL,
  `idproduct` INT NOT NULL,
  `rating` INT UNSIGNED NOT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`iduser`, `idproduct`),
  CONSTRAINT `fk_CustomerReviews_Users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `base`.`Users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomerReviews_Products1`
    FOREIGN KEY (`idproduct`)
    REFERENCES `base`.`Products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CustomerReviews_Products1_idx` ON `base`.`CustomerReviews` (`idproduct` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
